version: '3.1'

services:

  app:
    build: ./docker/app
    volumes:
      - ./src:/usr/src/myapp
    networks:
      - rust-app
    tty: true
    depends_on:
      - db

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - rust-app

networks:
  rust-app:
    driver: bridge